cdef str trc_grid(int G[9][9])
cdef str trc_cands(bint C[9][9][9])
cdef void *PyMem_TRCX_Malloc(size_t Bytes)
cdef void *PyMem_TRCX_Calloc(size_t Nr, size_t Bytes)
cdef void PyMem_TRCX_Free(void *Mem)
